---

kind: ConfigMap
apiVersion: v1
metadata:
  name: heymars
  namespace: default
data:
  default.json: |-
    {
        "message": "Hey Mars!"
    }

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: heymars
  name: heymars
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heymars
  template:
    metadata:
      labels:
        k8s-app: heymars
    spec:
      containers:
      - name: hello-world
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:node
        command:
        - npm
        args:
        - run
        - dev
        ports:
        - containerPort: 8080
        - containerPort: 5858
        volumeMounts:
        - name: code
          mountPath: /app
        - name: configuration
          mountPath: /app/config
      volumes:
      - name: code
        hostPath:
          path: /Users/MattPatt/src/t-mobile/ccp/learning/k8s-local-dev
      - name: configuration
        configMap:
          name: heymars

---

apiVersion: v1
kind: Service
metadata:
  name: heymars
  namespace: default
  labels:
    app: heymars
spec:
  selector:
    k8s-app: heymars
  ports:
  - name: app-port
    port: 8080
    nodePort: 30005
  - name: debug-port
    port: 9229
    nodePort: 30006
  type: NodePort
